In [1]:
%matplotlib inline
import re
import matplotlib
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd


In [3]:
# importing stopwords for Python 3 vs Python 2.7 is different. Follow the format below to import.

from nltk.corpus import stopwords
stop_words = set(stopwords.words('english'))
print(stop_words)

{'weren', 'won', 'few', 'as', 'are', 'm', "needn't", "shan't", 'of', 'o', 'each', 'its', 'y', "she's", 'over', 'they', 'further', 'll', 'most', 'can', "wouldn't", 'or', 'other', "didn't", 'then', 'he', 'mustn', 'doesn', 'any', 'doing', 'out', 'couldn', 'hadn', "wasn't", 'shouldn', 'our', 'had', 'under', 'for', "weren't", 'now', 'haven', "haven't", 'wasn', 'here', "hadn't", 't', 'yours', 's', 'her', 'their', 'd', 'about', 'don', "it's", 'is', 'will', 'hasn', 'ours', 'was', 'did', 'once', "won't", 'above', 'themselves', 'not', "aren't", 'whom', 'itself', 'where', 'up', 'have', 'before', 'on', 'aren', 'does', 'through', "you'd", 'she', 'but', 'why', 'during', 'your', 'because', 'it', 'and', 'which', 'again', "doesn't", 'them', 'we', 'until', 'who', 'shan', 'ma', 'between', 'so', 'against', 'myself', "couldn't", 'just', 'me', 'mightn', 'the', 'him', 'having', 'by', 'all', 'from', "don't", 'a', 'his', 'himself', 'if', 'with', 'to', 'after', 'in', 'down', 'these', 'theirs', 'such', 'my', 're

In [11]:
#stop_words = set(stopwords.words('english'))
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score
from sklearn.multiclass import OneVsRestClassifier
#from nltk.corpus import stopwords
#stop_words = set(stopwords.words('english'))
from sklearn.svm import LinearSVC
from sklearn.linear_model import LogisticRegression
from sklearn.pipeline import Pipeline
import seaborn as sns

In [ ]:
# Where is this file
df = pd.read_csv("WB_COMBINED_eng_es_utts_df_sents_pos.csv") #"WB_es_eng_lang_df_pos_training_set.csv token dataset 
df.head()

df_5 = df.head(5)

In [93]:
df['Speech'] = df['Speech'].str.strip()

In [101]:
df['Speech'] = df['Speech'].str.lower()

In [102]:
df.columns

Index(['Speech', 'word_dict', 'VERB', 'PRON', 'ADV', 'ADJ', 'DET', 'NOUN',
       'ADP', 'INTJ', 'PART', 'AUX', 'CCONJ', 'NUM', 'SCONJ', 'lang_en',
       'lang_es'],
      dtype='object')

In [103]:
df_classes = df.drop(columns=['Speech', 'word_dict'])

In [104]:
df_classes.shape

(50515, 15)

In [105]:
df_classes.columns

Index(['VERB', 'PRON', 'ADV', 'ADJ', 'DET', 'NOUN', 'ADP', 'INTJ', 'PART',
       'AUX', 'CCONJ', 'NUM', 'SCONJ', 'lang_en', 'lang_es'],
      dtype='object')

In [106]:
classes=[]

for row in df_classes.iterrows():
    index, data = row
    classes.append(data.tolist())

classes=np.array(classes)

classes

array([[0, 0, 0, ..., 0, 1, 0],
       [1, 1, 0, ..., 0, 1, 0],
       [0, 0, 0, ..., 0, 1, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 1],
       [1, 0, 0, ..., 0, 0, 1],
       [0, 0, 0, ..., 0, 0, 1]])

In [107]:
df['Speech'].fillna('', inplace=True)

In [108]:
text_list = list(df['Speech'])

text_list

['',
 'stop it',
 '',
 '',
 '',
 "she's so busy",
 '',
 '',
 'a book',
 '',
 'book',
 '',
 'what is daisy',
 'what is that',
 '',
 'me',
 '',
 'what is that',
 '',
 'you',
 '',
 'me',
 '',
 "that's a dog",
 '',
 'a dog',
 '',
 'a puppy',
 '',
 '',
 'look at daisy with the ball',
 '',
 'daisy ball',
 '',
 'daisy playing with the ball',
 'look at her playing with the ball on the couch',
 '',
 'yes',
 '',
 'with the ball',
 '',
 'hello',
 '',
 'the ball',
 "daisy's playing ball",
 '',
 '',
 "you'll see her stroller right there in front of the room",
 '',
 '',
 'excuse me',
 'look',
 'okay',
 'where is the dog',
 "where's daisy",
 'she sleeping on the couch',
 '',
 'sleeping the couch',
 '',
 '',
 '',
 '',
 'with the ball',
 '',
 'playing outside with the ball',
 '',
 'here',
 '',
 "what's that",
 '',
 'ball',
 '',
 'yes',
 'what color is that',
 '',
 'color',
 '',
 'red',
 '',
 'red',
 '',
 'bouncing the ball',
 '',
 '',
 'gate',
 '',
 'mm-hmm (affirmative)',
 'look',
 "now she's sad beca

In [109]:
import pickle

In [110]:
SVC_pipeline = Pipeline([
                ('tfidf', TfidfVectorizer()), #add your stop_words
                ('clf', OneVsRestClassifier(LinearSVC(), n_jobs=1)),
            ])
SVC_pipeline.fit(text_list, classes)

pickle.dump(SVC_pipeline,open('WB_SENT_POS_EN_ES_POS_WB_226.pickle', 'wb'))

In [40]:
obj = pickle.load(open('EN_ES_POS_WB_221.pickle', 'rb'))
obj.predict(["y","leer","you", "run"])

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0]])

In [151]:
obj = pickle.load(open('WB_SENT_POS_EN_ES_POS_WB_226.pickle', 'rb'))
obj.predict(['a puppy'])

array([[0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0]])

In [114]:
import glob
import datetime
# getting current date and time
d = datetime.datetime.today()
path = 'C:\\Users\\dbyrne\\Downloads\\text_files\\es_text_files'
all_files = glob.glob(path + "/*.txt")
print(all_files)


vs_number = 'VS4'

li = []

analyzed_speech = []

parent_sent_complexity_list = []
child_sent_complexity_list = []

for filename in all_files:
    df = pd.read_csv(filename, sep = ':', index_col=None, error_bad_lines=False, encoding='utf-8', header=None)
    li.append(df)

['C:\\Users\\dbyrne\\Downloads\\text_files\\es_text_files\\121_RC136_24MO_BSA.txt', 'C:\\Users\\dbyrne\\Downloads\\text_files\\es_text_files\\173_RC111_24MO_BSA.txt', 'C:\\Users\\dbyrne\\Downloads\\text_files\\es_text_files\\173_RC317_24MO_BSA.txt', 'C:\\Users\\dbyrne\\Downloads\\text_files\\es_text_files\\173_RC42_24MO_BSA.txt', 'C:\\Users\\dbyrne\\Downloads\\text_files\\es_text_files\\173_RC482_24MO_BSA_Pt1.txt', 'C:\\Users\\dbyrne\\Downloads\\text_files\\es_text_files\\173_RC482_24MO_BSA_Pt2.txt', 'C:\\Users\\dbyrne\\Downloads\\text_files\\es_text_files\\173_RC488_24MO_BSA.txt', 'C:\\Users\\dbyrne\\Downloads\\text_files\\es_text_files\\173_RC493_24MO_BSA.txt', 'C:\\Users\\dbyrne\\Downloads\\text_files\\es_text_files\\173_RC494_24MO_BSA.txt', 'C:\\Users\\dbyrne\\Downloads\\text_files\\es_text_files\\173_RC499_24MO_BSA_pt1.txt', 'C:\\Users\\dbyrne\\Downloads\\text_files\\es_text_files\\173_RC513_24MO_BSA_pt2.txt', 'C:\\Users\\dbyrne\\Downloads\\text_files\\es_text_files\\173_RC53_24MO

b'Skipping line 21: expected 2 fields, saw 3\nSkipping line 25: expected 2 fields, saw 4\nSkipping line 27: expected 2 fields, saw 3\nSkipping line 29: expected 2 fields, saw 3\n'
b'Skipping line 25: expected 2 fields, saw 3\nSkipping line 57: expected 2 fields, saw 3\n'
b'Skipping line 12: expected 2 fields, saw 3\n'
b'Skipping line 17: expected 2 fields, saw 3\n'
b'Skipping line 77: expected 2 fields, saw 4\n'
b'Skipping line 23: expected 2 fields, saw 3\nSkipping line 31: expected 2 fields, saw 3\nSkipping line 33: expected 2 fields, saw 3\n'
b'Skipping line 57: expected 2 fields, saw 3\nSkipping line 85: expected 2 fields, saw 3\n'
b'Skipping line 9: expected 2 fields, saw 3\n'
b'Skipping line 67: expected 2 fields, saw 3\nSkipping line 83: expected 2 fields, saw 3\n'
b'Skipping line 5: expected 2 fields, saw 3\nSkipping line 13: expected 2 fields, saw 3\nSkipping line 23: expected 2 fields, saw 3\n'
b'Skipping line 5: expected 2 fields, saw 3\n'
b'Skipping line 33: expected 2 fiel

In [115]:
def drop_filler(x):
    x = str(x)
    x = x.strip()
    x = x.split()
    word_list = []
    stop_phrases = ['[Unintelligible',  'speech]', '[Coughs]', '[Crying]', '[Laughing]', '[Laughs]', '[Whining]', 
                    '[Gasps]', '[Whispering]', '[Shrieks]']
    for word in x:
        if word in stop_phrases:
            word.replace(word, '')
        else:
            word_list.append(word)
    return ' '.join(word_list)

In [116]:
nli = []

for df in li:
    count = 0
    try:
        df[1]=df[1].map(lambda x: drop_filler(x))
        nli.append(df)
    except KeyError:
        continue

In [140]:
es_merged_df = pd.concat(nli, axis=0)

In [118]:
es_li_flat = []
for li in list(es_merged_df[1].map(lambda x: x.split())):
    for y in li:
        es_li_flat.append(y)

In [119]:
df_1=pd.DataFrame(es_li_flat)

In [120]:
import string

In [149]:
es_merged_df=es_merged_df[[0,1]]

In [121]:
df_1[0].map(lambda x: re.sub(r'[^\w\s]','', x.lower()))

0              ok
1        entonces
2            aquí
3             hay
4            unos
5          libros
6             con
7              un
8           total
9              de
10           mira
11           mira
12           mira
13           mira
14           mira
15           mira
16           mira
17           mira
18           mira
19             el
20           guau
21           guau
22             el
23           guau
24           guau
25           mira
26       pelotita
27           mira
28           mira
29            una
           ...   
49987         hes
49988     melting
49989        lets
49990         see
49991          is
49992          he
49993        okay
49994       there
49995          he
49996          is
49997         its
49998        okay
49999         its
50000        okay
50001        dino
50002       youre
50003        okay
50004         its
50005        okay
50006        dino
50007         its
50008        okay
50009        dino
50010         its
50011     

In [152]:
obj = obj.predict(list(es_merged_df[1].str.lower()))

In [155]:
obj=pd.DataFrame(obj)

In [139]:
es_merged_df

0                                                  1
0    Caregiver  Ok, entonces aquí hay unos libros, con un tota...
1        Child                                                   
2    Caregiver                                                   
3        Child                                                   
4    Caregiver                                        Mira, mira.
5        Child                                                   
6    Caregiver                                         Mira, mira
7        Child                                                   
8    Caregiver                            Mira, mira, mira, mira.
9        Child                                                   
10   Caregiver                                ¡Mira el guau guau!
11       Child                                                   
12   Caregiver                                                   
13       Child                                                   
14   Caregiver  El guau guau. Mira, pelotita. Mira, mira una p...
15       Child                                                   
16   Caregiver                                        Mira… mira…
17       Child                                                   
18   Caregiver                    Mira, mira, mira las pelotitas.
19       Child                                                   
20   Caregiver  el perrito con las pelotitas. Mira, está jugan...
21       Child                                                   
22   Caregiver                        Mira, anda caminando, mira.
23       Child                                                   
24   Caregiver  Mira, anda con sus amiguitos. Mira, anda con s...
25       Child                                                   
26   Caregiver                                  Mira, mira, mira.
27       Child                                                   
28   Caregiver     Mira, anda con sus amiguitos. ¿Ves, ves? Mira…
29       Child                                                   
..         ...                                                ...
129      Child                                          Bye, bye.
130      Child                                             Adiós.
131  Caregiver                                      Are you done?
132      Child                                      Are you done?
133      Child                                             Hello!
134  Caregiver                                           Come on.
135      Child                                           Come on.
136  Caregiver                                          Let´s go.
137      Child                                          Let´s go.
138  Caregiver                                          Bye, bye.
139      Child                                          Bye, bye.
140      Child                                         Thank you.
141  Caregiver                                              Okey.
142      Child                                                No.
143  Caregiver                                               ¿No?
144      Child                                     No. No, mommy.
145  Caregiver                      ¿No, baby? Mira, ¡es un baby!
146      Child                                                No.
147      Child                                            Má, má.
148  Caregiver                          Mira, la niña está slide.
149      Child                                             Slide.
150  Caregiver                    Se resbala por la resbaladilla.
151      Child                                       Oh, speech].
152  Caregiver  Miraaa. Mira el niño que está jugando con los ...
153      Child                                               Yes.
154  Caregiver                                         Mira, wow.
155      Child                                               Wow.
156  Caregiver                                      Wow. ¡Oh, no!
157      Child                                       

In [157]:
es_merged_df = es_merged_df.loc[~es_merged_df.index.duplicated(keep='first')]

In [158]:
es_test = pd.concat([es_merged_df, obj], axis=1, ignore_index=True)

In [160]:
es_test.to_csv('es_SENT_test_agnostic_bimodel.csv')

In [48]:
words = list(df_1[0])

In [52]:
es_test.head()

0   1   2   3   4   5   6   7   8   9   10  11  12  13  14  15  16  \
0       Ok,   0   0   0   0   0   1   0   0   0   0   0   0   0   0   0   0   
1  entonces   0   0   1   0   0   0   0   0   0   0   0   0   0   0   0   0   
2      aquí   0   0   1   0   0   0   0   0   0   0   0   0   0   0   0   0   
3       hay   0   0   0   0   0   0   0   0   0   0   0   0   1   0   0   0   
4      unos   0   1   0   0   0   0   0   0   0   0   0   0   0   0   0   0   

   17  
0   1  
1   1  
2   1  
3   1  
4   1

In [54]:
es_test.rename(columns={0: "Word", 1: "Verb", 2: "PRON", 3: "ADV",
                        4: "ADJ", 5: "DET", 6: "NOUN", 7: "NUM", 8: "ADP",
                        9: "PROPN", 10: "INTJ", 11: "X", 12: "CCONJ", 13: "AUX", 
                        14: "PART", 15: "SCONJ", 16:"Lang_en", 17: "Lang_es"}, inplace=True)

In [56]:
categories = es_test.drop(columns=['Word'])

In [64]:
train, test = train_test_split(es_test, random_state=42, test_size=.30, shuffle=True)
X_train = train.Word
X_test = test.Word
print(X_train.shape)
print(X_test.shape)

(35011,)
(15006,)


In [65]:
SVC_pipeline = Pipeline([
                ('tfidf', TfidfVectorizer(stop_words=stop_words)),
                ('clf', OneVsRestClassifier(LinearSVC(), n_jobs=1)),
            ])
for category in categories:
    print('... Processing {}'.format(category))
    # train the model using X_dtm & y
    SVC_pipeline.fit(X_train, train[category])
    # compute the testing accuracy
    prediction = SVC_pipeline.predict(X_test)
    print('Test accuracy is {}'.format(accuracy_score(test[category], prediction)))

... Processing Verb
Test accuracy is 0.9824070371851259
... Processing PRON
Test accuracy is 0.9748100759696121
... Processing ADV
Test accuracy is 0.9731440757030521
... Processing ADJ
Test accuracy is 0.9972677595628415
... Processing DET
Test accuracy is 0.9695455151272824
... Processing NOUN
Test accuracy is 0.9891376782620285
... Processing NUM
Test accuracy is 0.9999333599893376
... Processing ADP
Test accuracy is 0.9809409569505532
... Processing PROPN
Test accuracy is 0.9994002399040384
... Processing INTJ
Test accuracy is 0.9997334399573504
... Processing X
Test accuracy is 1.0
... Processing CCONJ
Test accuracy is 0.9974010395841664
... Processing AUX
Test accuracy is 0.9999333599893376
... Processing PART
Test accuracy is 1.0
... Processing SCONJ
Test accuracy is 1.0
... Processing Lang_en
Test accuracy is 0.9139677462348395
... Processing Lang_es
Test accuracy is 0.9139677462348395


In [3]:
obj = pickle.load(open('EN_ES_POS_WB_221.pickle', 'rb'))
obj.predict(["Leer","un","book"])

C:\Users\dbyrne\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\base.py:334: UserWarning: Trying to unpickle estimator TfidfTransformer from version 0.20.1 when using version 0.23.0. This might lead to breaking code or invalid results. Use at your own risk.
  UserWarning)
C:\Users\dbyrne\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\base.py:334: UserWarning: Trying to unpickle estimator TfidfVectorizer from version 0.20.1 when using version 0.23.0. This might lead to breaking code or invalid results. Use at your own risk.
  UserWarning)
C:\Users\dbyrne\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\utils\deprecation.py:143: FutureWarning: The sklearn.svm.classes module is  deprecated in version 0.22 and will be removed in version 0.24. The corresponding classes / functions should instead be imported from sklearn.svm. Anything that cannot be imported from sklearn.svm is now part of the private API.
  warnings.warn(message, FutureWarning)
C:\Users\d

array([[1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0]])

In [2]:
import pickle